/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProyeccionRouteImport } from './routes/_authenticated/proyeccion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAcademiaRouteImport } from './routes/_authenticated/academia'
import { Route as AuthenticatedCasosIndexRouteImport } from './routes/_authenticated/casos.index'
import { Route as AuthenticatedCasosIdRouteImport } from './routes/_authenticated/casos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProyeccionRoute = AuthenticatedProyeccionRouteImport.update({
  id: '/proyeccion',
  path: '/proyeccion',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcademiaRoute = AuthenticatedAcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasosIndexRoute = AuthenticatedCasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasosIdRoute = AuthenticatedCasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/academia': typeof AuthenticatedAcademiaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proyeccion': typeof AuthenticatedProyeccionRoute
  '/casos/$id': typeof AuthenticatedCasosIdRoute
  '/casos/': typeof AuthenticatedCasosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/academia': typeof AuthenticatedAcademiaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proyeccion': typeof AuthenticatedProyeccionRoute
  '/': typeof AuthenticatedIndexRoute
  '/casos/$id': typeof AuthenticatedCasosIdRoute
  '/casos': typeof AuthenticatedCasosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/academia': typeof AuthenticatedAcademiaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/proyeccion': typeof AuthenticatedProyeccionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/casos/$id': typeof AuthenticatedCasosIdRoute
  '/_authenticated/casos/': typeof AuthenticatedCasosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/academia'
    | '/dashboard'
    | '/proyeccion'
    | '/casos/$id'
    | '/casos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/academia'
    | '/dashboard'
    | '/proyeccion'
    | '/'
    | '/casos/$id'
    | '/casos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/academia'
    | '/_authenticated/dashboard'
    | '/_authenticated/proyeccion'
    | '/_authenticated/'
    | '/_authenticated/casos/$id'
    | '/_authenticated/casos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proyeccion': {
      id: '/_authenticated/proyeccion'
      path: '/proyeccion'
      fullPath: '/proyeccion'
      preLoaderRoute: typeof AuthenticatedProyeccionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academia': {
      id: '/_authenticated/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AuthenticatedAcademiaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/casos/': {
      id: '/_authenticated/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof AuthenticatedCasosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/casos/$id': {
      id: '/_authenticated/casos/$id'
      path: '/casos/$id'
      fullPath: '/casos/$id'
      preLoaderRoute: typeof AuthenticatedCasosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAcademiaRoute: typeof AuthenticatedAcademiaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProyeccionRoute: typeof AuthenticatedProyeccionRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCasosIdRoute: typeof AuthenticatedCasosIdRoute
  AuthenticatedCasosIndexRoute: typeof AuthenticatedCasosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcademiaRoute: AuthenticatedAcademiaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProyeccionRoute: AuthenticatedProyeccionRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCasosIdRoute: AuthenticatedCasosIdRoute,
  AuthenticatedCasosIndexRoute: AuthenticatedCasosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
